import { GoogleGenAI, Modality, Type } from '@google/genai';
import type { ImageStyle, Virtue, Calling, GeneratedCallingDetails } from '../types';

// This function converts a file to a base64 string
const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => {
            if (typeof reader.result === 'string') {
                // remove the header from the base64 string
                resolve(reader.result.split(',')[1]);
            } else {
                reject(new Error('Failed to convert file to base64'));
            }
        };
        reader.onerror = (error) => reject(error);
    });
};

const getImagePrompt = (callingName: string, style: ImageStyle): string => {
    const baseInstruction = `Transform this photo of a child into a beautiful illustration. **Crucially, preserve the child's unique facial features and likeness**, seamlessly integrating them into the artistic style. The child should be depicted as '${callingName}'. The final image should feel magical, warm, and inspiring. Avoid photorealism and uncanny valley effects where it doesn't fit the style. The style should be consistent with a high-end publication, capturing the essence of the child's personality from the original photo.`;

    switch (style) {
        case 'photorealistic':
            return `Transform this photo of a child into a stunning, photorealistic portrait. **Crucially, preserve the child's unique facial features and likeness**. The child should be depicted as '${callingName}' in a realistic setting. The lighting should be dramatic and the quality should be like a high-end magazine photo. The mood should be inspiring and powerful.`;
        case 'comic':
            return `Transform this photo of a child into a dynamic comic book style illustration. **Crucially, preserve the child's unique facial features and likeness**, adapting them to a graphic novel art style. Use bold lines, vibrant colors, and a sense of action or wonder. The child should be depicted as '${callingName}'. The result should feel like a page from a modern, high-quality comic book.`;
        case 'artistic':
        default:
             return `Transform this photo of a child into a beautiful, painterly storybook illustration in the style of Studio Ghibli. **Crucially, preserve the child's unique facial features and likeness**, seamlessly integrating them into the artistic style. The child should be depicted as '${callingName}'. The final image should feel magical, warm, and inspiring. Avoid photorealism and uncanny valley effects. The style should be consistent with a high-end children's book, capturing the essence of the child's personality from the original photo.`;
    }
};

export const generateStorybookImage = async (
    imageFile: File,
    callingName: string,
    style: ImageStyle
): Promise<string> => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable is not set.");
    }
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    const base64Image = await fileToBase64(imageFile);
    const mimeType = imageFile.type;

    const prompt = getImagePrompt(callingName, style);

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: base64Image,
                            mimeType: mimeType,
                        },
                    },
                    {
                        text: prompt,
                    },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });
        
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
            }
        }
        throw new Error("No image was generated by the API.");
    } catch (error) {
        console.error("Error generating storybook image:", error);
        throw new Error("Failed to generate the image. Please try again.");
    }
};

export const editStorybookImage = async (
    imageUrl: string,
    instruction: string
): Promise<string> => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable is not set.");
    }

    // Extract base64 and mimeType from data URL
    // Format: data:[<mediatype>][;base64],<data>
    const matches = imageUrl.match(/^data:(.+);base64,(.+)$/);
    if (!matches || matches.length !== 3) {
        throw new Error("Invalid image format. Must be a base64 Data URL.");
    }
    const mimeType = matches[1];
    const base64Image = matches[2];

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: base64Image,
                            mimeType: mimeType,
                        },
                    },
                    {
                        text: instruction,
                    },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
            }
        }
        throw new Error("No edited image was generated by the API.");
    } catch (error) {
         console.error("Error editing storybook image:", error);
         throw new Error("Failed to edit the image. Please try again.");
    }
};

export const generateCallingDetails = async (childsName: string, virtue: Virtue, calling: Calling): Promise<GeneratedCallingDetails> => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable is not set.");
    }
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const prompt = `The user is a child named ${childsName}. Their revealed 'spark' or core virtue is ${virtue.name}. They have chosen the calling of '${calling.name}'. Generate a JSON object with the following details for them:
    1.  'story': A short, magical, and inspiring story (2-3 paragraphs) about ${childsName} as ${calling.name}.
    2.  'roleModel': An object with 'name' and 'bio'. The bio should be a one-paragraph, child-friendly biography of a relevant real-world role model (from Indian or global history).
    3.  'skillPath': An object with 'title' and 'description'. The title should be based on craftsmanship concepts like 'The Path of the Shokunin' or 'The Way of the Artisan'. The description should be a short paragraph about the importance of focus, practice, and patience.
    4.  'firstStep': An object with 'title' and 'description'. The title should be based on kaizen, like 'Your First Small Step'. The description should be a simple, actionable daily habit a child can do related to the calling of ${calling.name}.
    `;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-pro',
            contents: prompt,
            config: {
                responseMimeType: 'application/json',
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        story: { type: Type.STRING },
                        roleModel: {
                            type: Type.OBJECT,
                            properties: {
                                name: { type: Type.STRING },
                                bio: { type: Type.STRING }
                            },
                             required: ['name', 'bio'],
                        },
                        skillPath: {
                            type: Type.OBJECT,
                            properties: {
                                title: { type: Type.STRING },
                                description: { type: Type.STRING }
                            },
                            required: ['title', 'description'],
                        },
                        firstStep: {
                            type: Type.OBJECT,
                            properties: {
                                title: { type: Type.STRING },
                                description: { type: Type.STRING }
                            },
                             required: ['title', 'description'],
                        }
                    },
                    required: ['story', 'roleModel', 'skillPath', 'firstStep']
                }
            }
        });
        
        const jsonText = response.text.trim();
        return JSON.parse(jsonText) as GeneratedCallingDetails;

    } catch (error) {
        console.error("Error generating calling details:", error);
        throw new Error("Failed to generate the story and details. Please try again.");
    }
};
